name: mime-type
on:
  push:
    tags:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main
      - devel

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2

      - name: Test
        run: cargo test

      - name: Doc Test
        run: cargo test --doc

  publish:
    name: Publish (crates.io)
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2

      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
